
<b><span style="color: red; font-family: Babas; font-size: 3em;">Just fun with Numpy</span></b>

>NumPy (short for **Numerical Python**) provides
an efficient interface to store and operate on dense data buffers. In some ways,
NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much
more efficient storage and data operations as the arrays grow larger in size. NumPy
arrays form the core of nearly the entire ecosystem of data science tools in Python, so
time spent learning to use NumPy effectively will be valuable no matter what aspect
of data science interests you.
![logo](doc\logo.jpeg)

In [1]:
#you can import NumPy and double-check the version:
import numpy
numpy.__version__

'1.15.1'

__you’ll find that most people in the SciPy/PyData world will
import NumPy using np as an alias:__

In [2]:
import numpy as np

In [3]:
dir(numpy)  # all functions in numpy

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

## Fixed-Type Arrays in Python
>_Python offers several different options for storing data in efficient, fixed-type data_
_buffers.The built-in array module (available since Python 3.3) can be used to create_
_dense arrays of a uniform type:_

**we’ll demonstrate several ways of creating a NumPy array.**

In [4]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain
the same type. If types do not match, NumPy will upcast if possible **(here, integers are
upcast to floating point):**

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
np.array([1, 2, 3, 4], dtype='float32') #If we want to explicitly set the data type of the resulting array.

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# nested lists multidimensional arrays
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
x=np.array([
           [[1,2,3],
            [4,5,6],
            [7,8,9]],
           [[10,20,30],
            [40,50,60],
            [70,80,90]]
         ])
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [9]:
# Create a length-10 integer array filled with zeros
print(np.zeros(10, dtype=int))
print(np.zeros((2,4), dtype=int))
print(np.zeros((2,4,5), dtype=int))

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]]
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [10]:
# Create a 3x1 floating-point array filled with 1s
a=np.ones(4)
print(a)

a=np.ones(4,dtype=int)
print(a)

a=np.ones((3, 1), dtype=float)
b=np.full((3, 2), 56)
print(a)
print(b)

[1. 1. 1. 1.]
[1 1 1 1]
[[1.]
 [1.]
 [1.]]
[[56 56]
 [56 56]
 [56 56]]


In [11]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 1, stepping by 0.1
# (this is similar to the built-in range() function)
np.arange(0, 1, 0.1) # simillar to seq command in R

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [12]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
#Create a 10x1 array of uniformly distributed
# random values between 0 and 1
np.random.random((10, 10))

array([[0.38907556, 0.95458908, 0.14770116, 0.80431875, 0.41998999,
        0.91652816, 0.11639273, 0.45610801, 0.06188537, 0.09588901],
       [0.14999749, 0.13622885, 0.33025204, 0.65601372, 0.3358168 ,
        0.58668519, 0.09821932, 0.60472986, 0.36425596, 0.3435838 ],
       [0.29057511, 0.7977929 , 0.90133943, 0.00210972, 0.58820492,
        0.81001173, 0.48378066, 0.56832637, 0.52161967, 0.1073026 ],
       [0.5458841 , 0.23538435, 0.6328746 , 0.95037877, 0.23848109,
        0.51736595, 0.8500067 , 0.84513309, 0.89799472, 0.22205015],
       [0.22551149, 0.33547202, 0.88063196, 0.96813322, 0.4394265 ,
        0.08301872, 0.95520291, 0.97755689, 0.03701105, 0.68988551],
       [0.17014972, 0.40401049, 0.65780519, 0.87807004, 0.46424379,
        0.24003552, 0.84236477, 0.22682566, 0.90819689, 0.1354615 ],
       [0.90727918, 0.19070296, 0.48621777, 0.03983592, 0.86634351,
        0.56275609, 0.56762407, 0.10043696, 0.84021062, 0.28970294],
       [0.31068547, 0.73526801, 0.0047730

In [14]:
print(np.random.normal(0, 1, 10),'\n')
np.random.normal()

[-1.35168807 -1.2825121  -1.54981244  0.5228198  -0.67967623  0.02089658
  1.05460001  0.7748791   0.09471022  1.88087112] 



0.5928291547841461

In [15]:
xx=np.array(["SDP","VMS","PVM"])
xx.dtype

dtype('<U3')

In [16]:
#sample command in R
np.random.choice(xx, 10, 1)

array(['VMS', 'SDP', 'PVM', 'SDP', 'SDP', 'PVM', 'PVM', 'SDP', 'SDP',
       'VMS'], dtype='<U3')

In [17]:
#help in python
np.random.choice?

In [18]:
#importing in another way
from numpy.random import choice as sdp
sdp(xx, 10, 1)

array(['PVM', 'PVM', 'VMS', 'VMS', 'PVM', 'PVM', 'SDP', 'PVM', 'PVM',
       'SDP'], dtype='<U3')

In [19]:
a=sdp
a(xx, 10, 1)

array(['PVM', 'VMS', 'VMS', 'SDP', 'VMS', 'VMS', 'PVM', 'SDP', 'PVM',
       'SDP'], dtype='<U3')

In [20]:
# Create a 10x1 array of random integers in the interval [0, 100)
print(np.random.randint(0, 100),'\n')
print(np.random.randint(100),'\n')
print(np.random.randint(0, 100, (10, 1)),'\n')
print(np.random.randint(100,size=(10,2)),'\n')


59 

81 

[[41]
 [56]
 [79]
 [18]
 [51]
 [36]
 [67]
 [58]
 [48]
 [64]] 

[[12 62]
 [16 43]
 [56 84]
 [93 32]
 [96 67]
 [25 47]
 [60 94]
 [98 28]
 [29  1]
 [77 25]] 



In [21]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NumPy Standard Data Types

The standard NumPy data types are listed in Table 2-1. Note that when constructing
an array, you can specify them using a string:

!["table for data types"](doc\table.png)

# <font color=red>We’ll cover a few categories of basic array manipulations here:</font>

>* _**Attributes of arrays**_<br>
   Determining the size, shape, memory consumption, and data types of arrays<br>
* _**Indexing of arrays**_<br>
    Getting and setting the value of individual array elements<br>
* _**Slicing of arrays**_<br>
    Getting and setting smaller subarrays within a larger array<br>
* _**Reshaping of arrays**_<br>
    Changing the shape of a given array<br>
* _**Joining and splitting of arrays**_<br>
    Combining multiple arrays into one, and splitting one array into many<br>

## NumPy Array Attributes
We’ll start by defining three random
arrays: a one-dimensional, two-dimensional, and three-dimensional array. We’ll use
NumPy’s random number generator.

In [22]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=10) # One-dimensional array
x2 = np.random.randint(10, size=(3, 8)) # Two-dimensional array
x3 = np.random.randint(10, size=(2, 4, 7)) # Three-dimensional array

In [23]:
print("x1 ndim: ", x1.ndim) 
print("x2 shape:", x2.shape) #shape of array 3*8
print("x3 size: ", x3.size) #total no. of elements 
print("dtype:", x3.dtype) #for data type
print("itemsize:", x3.itemsize, "bytes") #meomery size in byte of each element in array
print("nbytes:", x3.nbytes, "bytes") # total meomery size of array

x1 ndim:  1
x2 shape: (3, 8)
x3 size:  56
dtype: int32
itemsize: 4 bytes
nbytes: 224 bytes


## <font color=blue>Array Indexing</font>
>If you are familiar with Python’s standard list indexing, indexing in NumPy will feel
quite familiar. In a one-dimensional array, you can access the ith value (counting from
zero) by specifying the desired index in square brackets, just as with Python lists:

In [24]:
print(x1)
print(x1[0])
print("length of x1:",len(x1))

print("error occur")
print(x1[10])

[5 0 3 3 7 9 3 5 2 4]
5
length of x1: 10
error occur


IndexError: index 10 is out of bounds for axis 0 with size 10

In [25]:
print(x1[9])
x1[-1] #To index from the end of the array, you can use negative indices

4


4

In [26]:
#In a multidimensional array, you access items using a comma-separated tuple of indices:
print(x2)
print(x2[0, 0])
# modification in array
x2[0, 0] = 12
print(x2)

[[7 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3]
 [0 3 5 0 2 3 8 1]]
7
[[12  6  8  8  1  6  7  7]
 [ 8  1  5  9  8  9  4  3]
 [ 0  3  5  0  2  3  8  1]]


In [27]:
x2[0,0] = 3.14159 # this will be truncated!
x2

array([[3, 6, 8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9, 4, 3],
       [0, 3, 5, 0, 2, 3, 8, 1]])

## Array Slicing: Accessing Subarrays
>we can also use them to access subarrays with the slice notation, marked by the colon (:) character.The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:<br>```x[start:stop:step]```<br><br>

**One-dimensional subarrays:**

In [28]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
print(x[:5]) # first five elements
print(x[5:]) # elements after index 5
print(x[4:7]) # middle subarray
print(x[::2]) # every other element
print(x[1::2]) # every other element, starting at index 1
print(x[0::2]) # even numbers

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[0 2 4 6 8]


In [30]:
print(x[::-1]) # all elements, reversed
print(x[5::-2] ) # reversed every other from index 5
print(x[5::2] )

[9 8 7 6 5 4 3 2 1 0]
[5 3 1]
[5 7 9]


**Multidimensional subarrays:**

In [31]:
print(x2)

[[3 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3]
 [0 3 5 0 2 3 8 1]]


In [32]:
print(x2[:2, :3] ,'\n') # two rows, three columns
print(x2[:3, ::2]) # all rows, every other column

[[3 6 8]
 [8 1 5]] 

[[3 8 1 7]
 [8 5 8 4]
 [0 5 2 8]]


In [33]:
x2[::-1, ::-1] #subarray dimensions can even be reversed together

array([[1, 8, 3, 2, 0, 5, 3, 0],
       [3, 4, 9, 8, 9, 5, 1, 8],
       [7, 7, 6, 1, 8, 8, 6, 3]])

In [34]:
print(x2[:, 0]) # first column of x2
print(x2[0, :]) # first row of x2
print(x2[0]) # equivalent to x2[0, :]

[3 8 0]
[3 6 8 8 1 6 7 7]
[3 6 8 8 1 6 7 7]


**<font color=red>Subarrays as no-copy views</font>**<br>
>_One important—and extremely useful—thing to know about array slices is that they
return views rather than copies of the array data. This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies. Consider our
two-dimensional array from before:_


In [35]:
print(x2)
x2_sub = x2[:2, :2]
print(x2_sub)

x2_sub[0, 0] = 99
print(x2_sub)

[[3 6 8 8 1 6 7 7]
 [8 1 5 9 8 9 4 3]
 [0 3 5 0 2 3 8 1]]
[[3 6]
 [8 1]]
[[99  6]
 [ 8  1]]


In [36]:
print(x2)

[[99  6  8  8  1  6  7  7]
 [ 8  1  5  9  8  9  4  3]
 [ 0  3  5  0  2  3  8  1]]


**Creating copies of arrays<br>**
>Despite the nice features of array views, it is sometimes useful to instead explicitly
copy the data within an array or a subarray. This can be most easily done with the
copy() method:

In [37]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[99  6]
 [ 8  1]]
[[42  6]
 [ 8  1]]


In [38]:
print(x2)

[[99  6  8  8  1  6  7  7]
 [ 8  1  5  9  8  9  4  3]
 [ 0  3  5  0  2  3  8  1]]


## Reshaping of Arrays
Another useful type of operation is reshaping of arrays. The most flexible way of
doing this is with the reshape() method.

In [39]:
a= np.arange(1, 10).reshape((3, 3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
x = np.array([1, 2, 3])
# row vector via reshape
print(x.reshape((1, 3)))
print(x.shape)

[[1 2 3]]
(3,)


In [41]:
# column vector via newaxis
print(x[:, np.newaxis])
x.shape

[[1]
 [2]
 [3]]


(3,)

## Array Concatenation and Splitting
>All of the preceding routines worked on single arrays. It’s also possible to combine
multiple arrays into one, and to conversely split a single array into multiple arrays.
We’ll take a look at those operations here.<br>

**Concatenation of arrays:**<br>
Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines `np.concatenate`, `np.vstack`, and `np.hstack`. `np.concatenate`
takes a tuple or list of arrays as its first argument, as we can see here:

In [42]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [43]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])
#concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [45]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

**Splitting of arrays**<br>
>The opposite of concatenation is splitting, which is implemented by the functions
`np.split`, `np.hsplit`, and `np.vsplit`. For each of these, we can pass a list of indices
giving the split points:

In [46]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [47]:
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print("upper\n",upper)
print("lower\n",lower)
left, right = np.hsplit(grid, [2])
print("left\n",left)
print("right\n",right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
upper
 [[0 1 2 3]
 [4 5 6 7]]
lower
 [[ 8  9 10 11]
 [12 13 14 15]]
left
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions
>Computation on NumPy arrays can be very fast, or it can be very slow. The key to
making it fast is to use vectorized operations, generally implemented through Num‐
Py’s `universal functions (ufuncs)`. This section motivates the need for NumPy’s ufuncs,
which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs
available in the NumPy package.

In [48]:
#The Slowness of Loops
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
print(compute_reciprocals(values))
%timeit compute_reciprocals(values)

[0.16666667 1.         0.25       0.25       0.125     ]
9.51 µs ± 71.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [49]:
print(1.0 / values)
%timeit (1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
918 ns ± 6.84 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Exploring NumPy’s UFuncs
>Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary
ufuncs, which operate on two inputs. We’ll see examples of both these types of functions
here.<br><br>

**Array arithmetic**
![title](doc\math.png)

In [50]:
x = np.arange(4)
print(x)
print("x + 5 =", x + 5)
print("x // 2 =", x // 2) # floor division

[0 1 2 3]
x + 5 = [5 6 7 8]
x // 2 = [0 0 1 1]


In [51]:
print(np.add(x, 2))
x = np.array([-2, -1, 0, 1, 2])
np.absolute(x)

[2 3 4 5]


array([2, 1, 0, 1, 2])

In [52]:
#Exponents and logarithms
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


**Aggregate Functions**
For binary ufuncs, there are some interesting aggregates that can be computed
directly from the object.<br>*below table provides a list of useful aggregation functions available in NumPy.*
![image.png](doc\aggr.png)

In [53]:
x = np.arange(1, 6)
print(np.add.reduce(x))
print(np.sum(x))
print(np.multiply.reduce(x))
print(np.cumsum(x)) # for cumsum
print(np.cumprod(x)) #for cumulative product

15
15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [54]:
#Outer products
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# Computation on Arrays: Broadcasting
>We saw in the previous section how NumPy’s universal functions can be used to vectorize
operations and thereby remove slow Python loops. Another means of vectorizing
operations is to use NumPy’s broadcasting functionality. Broadcasting is simply a
set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on
arrays of different sizes.

In [55]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

**Broadcasting allows these types of binary operations to be performed on arrays of different
sizes—for example, we can just as easily add a scalar (think of it as a zerodimensional
array) to an array:**

In [56]:
a + 5

array([5, 6, 7])

>*We can think of this as an operation that stretches or duplicates the value 5 into the
array `[5, 5, 5]`, and adds the results. The advantage of NumPy’s broadcasting is that
this duplication of values does not actually take place, but it is a useful mental model
as we think about broadcasting.*

In [57]:
M = np.ones((3, 3))
print(M)
print('\nans\n',M + a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

ans
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


>**<font color=red>Here the one-dimensional array a is stretched, or broadcast, across the second
dimension in order to match the shape of M.</font>**

In [58]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [59]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Visualization of NumPy broadcasting
_Just as before we stretched or broadcasted one value to match the shape of the other,
here we’ve stretched both a and b to match a common shape, and the result is a twodimensional
array! The geometry of these examples is visualized in Figure below_
![title](doc\bor.png)

## Rules of Broadcasting
**Broadcasting in NumPy follows a strict set of rules to determine the interaction
between the two arrays:**
>* **Rule 1**: If the two arrays differ in their number of dimensions, the shape of the
one with fewer dimensions is padded with ones on its leading (left) side.
* **Rule 2**: If the shape of the two arrays does not match in any dimension, the array
with shape equal to 1 in that dimension is stretched to match the other shape.
* **Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is
raised.

In [60]:
#example
M = np.ones((2, 3))
a = np.arange(3)
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

# Comparisons, Masks, and Boolean Logic
_**A summary of the comparison operators and their equivalent ufunc
is shown here:**_
![title](doc\logic.png)

In [61]:
x = np.array([1, 2, 3, 4, 5])
x < 3 # less than

array([ True,  True, False, False, False])

In [62]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

## Working with Boolean Arrays
**Counting entries**<br>To count the number of True entries in a Boolean array, np.count_nonzero is useful:

In [63]:
# how many values less than 6?
x = np.array([1, 2, 3, 4, 5,7,9,2])
np.count_nonzero(x < 6)

6

If we’re interested in quickly checking whether any or all the values are true, we can
use (you guessed it) `np.any()` or `np.all()`:

In [64]:
# are there any values greater than 8?
np.any(x > 8)

True

In [65]:
# are there any values less than zero?
np.any(x < 0)

False

**Boolean operators**
![title](doc\bool.png)

In [66]:
x = np.array([1, 2, 3, 4, 5,7,9,2])
np.sum((x> 3) & (x < 7))

2

**Boolean Arrays as Masks**<br>
Now to select these values from the array, we can simply index on this Boolean array;
this is known as a masking operation:

In [67]:
x[x<5]

array([1, 2, 3, 4, 2])

## <font color= green> Fancy Indexing </font>
>_**Fancy indexing is like the simple indexing we’ve already seen, but we pass
arrays of indices in place of single scalars. This allows us to very quickly access and
modify complicated subsets of an array’s values.**_

In [68]:
import numpy as np
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)
[x[3], x[7], x[2]]

[51 92 14 71 60 20 82 86 74 74]


[71, 86, 14]

In [69]:
#fancy index 
ind = [3, 7, 2]
x[ind]

array([71, 86, 14])

In [70]:
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

**Modifying Values with Fancy Indexing**<br>
>*Just as fancy indexing can be used to access parts of an array, it can also be used to
modify parts of an array. For example, imagine we have an array of indices and we’d
like to set the corresponding items in an array to some value:*


In [71]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)
x[i] -= 10
print(x)

[ 0 99 99  3 99  5  6  7 99  9]
[ 0 89 89  3 89  5  6  7 89  9]


# Sorting Arrays
>**Fast Sorting in NumPy: `np.sort` and `np.argsort`**<br>
To return a sorted version of the array without modifying the input, you can use
`np.sort`.<br><br>A related function is ```argsort```, which instead returns the indices of the sorted
elements:

In [72]:
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))
print(np.argsort(x))

[1 2 3 4 5]
[1 0 3 2 4]


**Sorting along rows or columns**
>A useful feature of NumPy’s sorting algorithms is the ability to sort along specific
rows or columns of a multidimensional array using the axis argument. For example:

In [73]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)
# sort each column of X
np.sort(X, axis=0)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [74]:
#Partial Sorts: Partitioning
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

# <font color=green>Structured Data: NumPy’s Structured Arrays</font>
>While often our data can be well represented by a homogeneous array of values,
sometimes this is not the case. This section demonstrates the use of NumPy’s structured
arrays and record arrays, which provide efficient storage for compound, heterogeneous data.<br>
_**for Example**, Imagine that we have several categories of data on a number of people (say, name,
age, and weight), and we’d like to store these values for use in a Python program. It
would be possible to store these in three separate arrays:_


In [75]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [76]:
#Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
'formats':('U10', 'i4', 'f8')})
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [77]:
# Get all names
print(data['name'])

# Get names where age is under 30
print(data[data['age'] < 30]['name'])

['Alice' 'Bob' 'Cathy' 'Doug']
['Alice' 'Doug']


In [78]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

>**The shortened string format codes may seem confusing, but they are built on simple
principles. The first (optional) character is < or >, which means “little endian” or “big
endian,” respectively, and specifies the ordering convention for significant bits. The
next character specifies the type of data: characters, bytes, ints, floating points, and so
on (see Table 2-4). The last character or characters represents the size of the object in
    bytes.**
    ![title](doc/dtype.png)

![thanks](doc\thanks.jpg)